const siteData = {
    "en": {
        "nav_about": "About",
        "nav_expertise": "Expertise",
        "nav_portfolio": "Portfolio",
        "nav_contact": "Contact",
        "nav_cv": "Download CV",
        "hero_greeting": "Hello, I'm",
        "hero_name": "Dr. Gelar Budiman, S.T., M.T.",
        "hero_role": "Lecturer & Researcher at Telkom University",
        "hero_desc": "Specializing in Classical and Quantum Signal Processing, Watermarking, Compressed Sensing, and Multimedia Systems.",
        "btn_contact": "Get In Touch",
        "btn_cv": "View Full CV",
        "section_about": "About Me",
        "about_text": "I am a dedicated Lecturer and Researcher based in Bandung, Indonesia, with extensive experience in Signal Processing, Communication Systems, and Watermarking.",
        "edu_title": "Education",
        "edu_1_degree": "Doctoral Degree",
        "edu_1_uni": "Institut Teknologi Bandung (ITB)",
        "edu_1_field": "Electrical Engineering (STEI)",
        "edu_1_year": "2015 - 2021",
        "edu_1_thesis": "Thesis: Audio Watermarking",
        "edu_2_degree": "Master Degree",
        "edu_2_uni": "Institut Teknologi Telkom",
        "edu_2_field": "Electro-Telecommunications",
        "edu_2_year": "2003 - 2005",
        "edu_2_thesis": "Thesis: Configuring MIMO MC-CDMA on Rayleigh Fading Canal",
        "edu_3_degree": "Undergraduate Degree",
        "edu_3_uni": "Institut Teknologi Telkom",
        "edu_3_field": "Electro-Telecommunications",
        "edu_3_year": "1997 - 2002",
        "edu_3_thesis": "Thesis: Semi-Adaptive TMS320C5x Equalizer implementation",
        "section_expertise": "Expertise & Skills",
        "exp_1": "Classical & Quantum Signal Processing",
        "exp_2": "Watermarking & Steganography",
        "exp_3": "Compressed Sensing",
        "exp_4": "Multimedia Systems",
        "exp_5": "Audio & Image Signal Processing",
        "exp_6": "Mobile Apps Development",
        "exp_7": "Wireless Communications",
        "exp_8": "Artificial Intelligence",
        "course_title": "Courses Taught",
        "course_1": "Linear Signal & System",
        "course_2": "Digital Signal Processing",
        "course_3": "Communication System",
        "course_4": "Computer Vision",
        "course_5": "Watermarking & Steganography",
        "course_6": "Coding & Compression",
        "course_7": "Microprocessor & Interface",
        "course_8": "Mobile Application",
        "course_9": "Speech Processing",
        "course_10": "AI for Wireless Communications",
        "section_portfolio": "Selected Research & Publications",
        "port_1_type": "Research",
        "port_1_title": "Compressive Sensing in Audio Watermarking for Content Security and Data Efficiency",
        "port_1_year": "2021",
        "port_2_type": "Journal",
        "port_2_title": "A Novel Approach: Effective Compressive Sensing in Power Network Problem",
        "port_2_year": "2021 - Journal of Hunan University Natural Sciences",
        "port_3_type": "Conference",
        "port_3_title": "Wavelet-Based Hybrid Audio Watermarking Using Statistical Mean Manipulation and Spread Spectrum",
        "port_3_year": "2020 - 27th International Conference on Telecommunications",
        "port_4_type": "Research",
        "port_4_title": "Implementation of DWT-Based Audio Watermarking Using SMM On Raspberry Pi",
        "port_4_year": "2020",
        "btn_view_all_pubs": "View All 53 Publications & 27 Research",
        "section_hki": "Patents & Intellectual Property (HKI)",
        "hki_1": "Aplikasi Stegacitra (2016)",
        "hki_2": "Stegakompresi : 091082 (2017)",
        "hki_3": "CSTV : 000175914 (2019)",
        "hki_4": "Autermarqss : 000202420 (2020)",
        "hki_5": "APK-CM : 000193936 (2020)",
        "hki_6": "LiW-ACS : 000269358 (2021)",
        "section_contact": "Contact Me",
        "contact_desc": "Feel free to reach out for research collaborations, academic inquiries, or professional consultations.",
        "footer_text": "© 2026 Gelar Budiman. All rights reserved.",
        "contact_email": "gelarbudiman@telkomuniversity.ac.id",
        "contact_phone": "+6281322045924",
        "contact_address": "Jl. Telekomunikasi Terusan Buahbatu Bandung, Indonesia",
        "contact_label_email": "Email",
        "contact_label_phone": "Phone",
        "contact_label_address": "Address"
    },
    "id": {
        "nav_about": "Tentang",
        "nav_expertise": "Keahlian",
        "nav_portfolio": "Portofolio",
        "nav_contact": "Kontak",
        "nav_cv": "Unduh CV",
        "hero_greeting": "Halo, Saya",
        "hero_name": "Dr. Gelar Budiman, S.T., M.T.",
        "hero_role": "Dosen & Peneliti di Telkom University",
        "hero_desc": "Bespecialisasi dalam Pemrosesan Sinyal Klasik dan Kuantum, Watermarking, Compressed Sensing, serta Sistem Multimedia.",
        "btn_contact": "Hubungi Saya",
        "btn_cv": "Lihat CV Lengkap",
        "section_about": "Tentang Saya",
        "about_text": "Saya adalah seorang Dosen dan Peneliti yang berdomisili di Bandung, Indonesia, dengan pengalaman mendalam di bidang Pemrosesan Sinyal, Sistem Komunikasi, dan Watermarking.",
        "edu_title": "Pendidikan",
        "edu_1_degree": "Doktoral (S3)",
        "edu_1_uni": "Institut Teknologi Bandung (ITB)",
        "edu_1_field": "Teknik Elektro (STEI)",
        "edu_1_year": "2015 - 2021",
        "edu_1_thesis": "Disertasi: Audio Watermarking",
        "edu_2_degree": "Magister (S2)",
        "edu_2_uni": "Institut Teknologi Telkom",
        "edu_2_field": "Teknik Telekomunikasi",
        "edu_2_year": "2003 - 2005",
        "edu_2_thesis": "Tesis: Configuring MIMO MC-CDMA on Rayleigh Fading Canal",
        "edu_3_degree": "Sarjana (S1)",
        "edu_3_uni": "Institut Teknologi Telkom",
        "edu_3_field": "Teknik Telekomunikasi",
        "edu_3_year": "1997 - 2002",
        "edu_3_thesis": "Tugas Akhir: Semi-Adaptive TMS320C5x Equalizer implementation",
        "section_expertise": "Keahlian & Minat",
        "exp_1": "Pemrosesan Sinyal Klasik & Kuantum",
        "exp_2": "Watermarking & Steganografi",
        "exp_3": "Compressed Sensing",
        "exp_4": "Sistem Multimedia",
        "exp_5": "Pemrosesan Sinyal Audio & Citra",
        "exp_6": "Pengembangan Aplikasi Mobile",
        "exp_7": "Komunikasi Nirkabel (Wireless)",
        "exp_8": "Kecerdasan Buatan (AI)",
        "course_title": "Mata Kuliah",
        "course_1": "Sinyal & Sistem Linier",
        "course_2": "Pemrosesan Sinyal Digital",
        "course_3": "Sistem Komunikasi",
        "course_4": "Computer Vision",
        "course_5": "Watermarking & Steganografi",
        "course_6": "Koding & Kompresi",
        "course_7": "Mikroprosesor & Antarmuka",
        "course_8": "Aplikasi Mobile",
        "course_9": "Pemrosesan Suara",
        "course_10": "AI untuk Komunikasi Nirkabel",
        "section_portfolio": "Riset & Publikasi Pilihan",
        "port_1_type": "Riset",
        "port_1_title": "Penerapan Compressive Sensing Pada Audio Watermarking Untuk Pengamanan Konten Dan Efisiensi Data",
        "port_1_year": "2021",
        "port_2_type": "Jurnal",
        "port_2_title": "A Novel Approach: Effective Compressive Sensing in Power Network Problem",
        "port_2_year": "2021 - Journal of Hunan University Natural Sciences",
        "port_3_type": "Konferensi",
        "port_3_title": "Wavelet-Based Hybrid Audio Watermarking Using Statistical Mean Manipulation and Spread Spectrum",
        "port_3_year": "2020 - 27th International Conference on Telecommunications",
        "port_4_type": "Riset",
        "port_4_title": "Implementasi Audio Watermarking Berbasis DWT Menggunakan SMM Pada Raspberry Pi",
        "port_4_year": "2020",
        "btn_view_all_pubs": "Lihat Semua 53 Publikasi & 27 Riset",
        "section_hki": "Paten & HKI",
        "hki_1": "Aplikasi Stegacitra (2016)",
        "hki_2": "Stegakompresi : 091082 (2017)",
        "hki_3": "CSTV : 000175914 (2019)",
        "hki_4": "Autermarqss : 000202420 (2020)",
        "hki_5": "APK-CM : 000193936 (2020)",
        "hki_6": "LiW-ACS : 000269358 (2021)",
        "section_contact": "Hubungi Saya",
        "contact_desc": "Silakan hubungi saya untuk kolaborasi riset, pertanyaan akademis, atau konsultasi profesional.",
        "footer_text": "© 2026 Gelar Budiman. Seluruh hak cipta dilindungi.",
        "contact_email": "gelarbudiman@telkomuniversity.ac.id",
        "contact_phone": "+6281322045924",
        "contact_address": "Jl. Telekomunikasi Terusan Buahbatu Bandung, Indonesia",
        "contact_label_email": "Email",
        "contact_label_phone": "Telepon",
        "contact_label_address": "Alamat"
    }
};
